/// Flutter icons ZeusIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ZeusIcon
///      fonts:
///       - asset: fonts/Zeus.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Zeus {
  Zeus._();

  static const _fontFamily = 'Zeus';
  static const IconData icon = IconData(0xe800, fontFamily: _fontFamily);
}
